spring:
  datasource:
    url: jdbc:mysql://database1.cymo4x1xzhys.ap-northeast-2.rds.amazonaws.com:3306/nintendo-ott
    username: admin
    password: pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  profiles:
    include: core

server:
  port: 8080

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: false
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
    schema-location-pattern: "**/*.graphql"
    introspection-enabled: true