spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://database1.cymo4x1xzhys.ap-northeast-2.rds.amazonaws.com:3306/nintendo-ott
#    username: admin
#    password: nintendo
#    url:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#    database: mysql
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  profiles:
    include: core
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: false
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
    schema-location-pattern: "**/*.graphql"
    introspection-enabled: true